import { component } from 'haunted';
import Button from './src/Button';
import Input from './src/Input';
import Checkbox from './src/Checkbox';
import Content from './src/Content';
import FooterContainer from './src/FooterContainer';
import Logo from './src/Logo';
import Navbar from './src/Navbar';
import Text from './src/Text';
import Title from './src/Title';
